### ISSUE TITLE
MalmoPython built with system libxerces-c instead of the one in conda

### ISSUE THREAD

**Issue by show0k** [spMohanty/malmo-conda-recipe#1]
Hi,
I installed  xerces-c 3.1 from homebrew to be able to start MalmoPython released by Microsoft, but it makes it impossible to start your version.
I suppose you should remove  xerces-c from homebrew before compiling.

``` bash
python -c "import MalmoPython"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/showok/miniconda/envs/malmo/lib/python2.7/site-packages/MalmoPython.so, 2): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.2.dylib
  Referenced from: /Users/showok/miniconda/envs/malmo/lib/python2.7/site-packages/MalmoPython.so
  Reason: image not found
```

**Comment by spMohanty** [comment]
Weird, because I already include `xerces-c` as a dependency.
I use the one from the `conda-forge` channel.

The necessary line is here : https://github.com/spMohanty/malmo-conda-recipe/blob/master/meta.yaml#L34

Also, are you talking about using the environment I released here : https://anaconda.org/crowdAI/malmo ?

or building it yourself using the conda recipes I released in this repository ?

**Comment by show0k** [comment]
It seems to be a bug from my side, I must have remove accidentally xerces-c conda package. I'm closing it.
